### ISSUE TITLE
Deployment Link not working

### ISSUE THREAD

**Issue by rohan9024** [rohan9024/ecommerce#59]
After clicking on this link, the website is not showing up -->
https://donation-box-1fin.vercel.app/

![image](https://user-images.githubusercontent.com/64919642/207626150-2f0cff91-d03f-42ac-afa4-a34c0df7e90b.png)

Whoever solves this issue will be rewarded 20 points

**Comment by kshitij01042002** [comment]
Assign me this issue. I have  figured out a way to resolve this

**Comment by Dibyendu303** [comment]
Please assign me @rohan9024

**Comment by rohan9024** [comment]
@kshitij01042002 go for it

**Comment by kshitij01042002** [comment]
@rohan9024 I deployed the app in my own versile environment to reproduce the problem.
Soo here's what I found

The problem occurs due to environment variables not been set in deployment mode.

Here you have to do some steps to avoid crash

First go to your versile console there in your projects:- 
![Screenshot 2022-12-14 230416](https://user-images.githubusercontent.com/91470808/207668064-6f147086-ce76-42d4-9242-f0a0535162e9.png)

Go to settings and in setting set the environment variables:- 

![Screenshot 2022-12-14 230452](https://user-images.githubusercontent.com/91470808/207668374-146a1bc7-2aab-446e-96c6-6b210e0beaef.png)

The environment variables are:-
`Environmnet Variables

    REACT_APP_APIKEY=
    REACT_APP_AUTHDOMAIN=
    REACT_APP_PROJECTID=
    REACT_APP_STORAGEBUCKET=
    REACT_APP_MESSAGINGSENDERID=
    REACT_APP_APPID=
    REACT_APP_MEASUREMENTID=
`

same as we do in .env file

This should solve the issue. Revert me if the issue persists

**Comment by rohan9024** [comment]
@kshitij01042002 giving you some points for working on this

**Comment by kshitij01042002** [comment]
> @kshitij01042002 no tried that as well still it doesn't work
> 
> Thank you so much that you have made so much efforts but I don't think we need a database or backend for now......
> 
> You guys can add more features in frontend 🚀

just follow the instructions in #62 and instead of pasting API values in .env file give them in versil environment and it should work fine
